import { StyleSheet } from "react-native";
import { colors, spacing } from "../../theme/theme";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: colors.background,
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  content: {
    padding: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
  },
  title: {
    color: colors.ink,
    fontSize: 32,
    fontWeight: "900",
    marginBottom: spacing.lg,
  },
  label: {
    color: colors.muted,
    fontWeight: "800",
    marginBottom: spacing.xs,
    marginTop: spacing.md,
  },
  input: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    color: colors.ink,
    padding: spacing.md,
  },
  purposeInput: {
    lineHeight: 20,
    minHeight: 92,
  },
  iconSummary: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 64,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  iconSummaryOpen: {
    borderColor: colors.accentDark,
  },
  iconSummaryPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.99 }],
  },
  iconPreview: {
    alignItems: "center",
    borderRadius: 14,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  iconPreviewEmoji: {
    fontSize: 24,
    lineHeight: 28,
  },
  iconSummaryCopy: {
    flex: 1,
    justifyContent: "center",
    marginLeft: spacing.sm,
  },
  iconSummaryMeta: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "800",
  },
  iconSummaryAction: {
    color: colors.accentDark,
    fontSize: 13,
    fontWeight: "900",
    marginLeft: spacing.sm,
  },
  iconPicker: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    marginTop: spacing.sm,
    overflow: "hidden",
    paddingHorizontal: spacing.xs,
    paddingTop: spacing.xs,
  },
  iconPickerExpanded: {
    borderRadius: 24,
  },
  iconPickerHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingBottom: spacing.sm,
  },
  iconPickerSizeButton: {
    alignItems: "center",
    borderRadius: 999,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  iconPickerPressed: {
    opacity: 0.72,
  },
  iconEmojiScroll: {
    maxHeight: 260,
  },
  iconEmojiScrollExpanded: {
    maxHeight: 560,
  },
  iconEmojiScrollContent: {
    paddingBottom: 58,
  },
  iconEmojiSection: {
    paddingBottom: spacing.md,
  },
  iconEmojiSectionTitle: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "900",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  iconEmojiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    paddingBottom: spacing.xs,
  },
  iconEmojiButton: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: "transparent",
    borderRadius: 999,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  iconEmojiButtonSelected: {
    backgroundColor: colors.background,
    borderColor: colors.accentDark,
  },
  iconEmojiGlyph: {
    fontSize: 22,
    lineHeight: 26,
    textAlign: "center",
  },
  iconNavBar: {
    alignItems: "center",
    backgroundColor: "rgba(29, 27, 24, 0.74)",
    borderRadius: 999,
    bottom: spacing.sm,
    flexDirection: "row",
    justifyContent: "space-around",
    left: spacing.sm,
    minHeight: 44,
    paddingHorizontal: 6,
    position: "absolute",
    right: spacing.sm,
  },
  iconNavButton: {
    alignItems: "center",
    borderRadius: 999,
    height: 36,
    justifyContent: "center",
    width: 30,
  },
  iconNavGlyph: {
    color: colors.surface,
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 22,
    textAlign: "center",
  },
  colorGrid: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    padding: spacing.md,
  },
  colorTileSelected: {
    borderColor: colors.ink,
  },
  colorTilePressed: {
    opacity: 0.72,
    transform: [{ scale: 0.94 }],
  },
  colorSwatch: {
    alignItems: "center",
    borderColor: colors.surface,
    borderRadius: 18,
    borderWidth: 3,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  colorCheck: {
    color: colors.surface,
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 20,
    textShadowColor: "rgba(0, 0, 0, 0.35)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  section: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "900",
    marginTop: spacing.lg,
  },
  parentSummary: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    marginTop: spacing.xs,
    minHeight: 60,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  parentSummaryPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.99 }],
  },
  parentSummaryIcon: {
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: 12,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  parentSummaryIconText: {
    fontSize: 20,
  },
  parentSummaryCopy: {
    flex: 1,
    marginLeft: spacing.sm,
  },
  parentSummaryTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "900",
  },
  parentSummaryMeta: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
  parentSummaryAction: {
    color: colors.accentDark,
    fontSize: 13,
    fontWeight: "900",
    marginLeft: spacing.sm,
  },
  modalScreen: {
    backgroundColor: colors.background,
  },
  modalContent: {
    padding: spacing.lg,
    paddingBottom: 60,
  },
  modalHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: spacing.lg,
  },
  modalTitle: {
    color: colors.ink,
    fontSize: 28,
    fontWeight: "900",
  },
  modalClose: {
    color: colors.accentDark,
    fontWeight: "800",
  },
  modalSection: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "900",
    marginTop: spacing.lg,
  },
  emptyPickerText: {
    color: colors.muted,
    marginTop: spacing.sm,
  },
  homeChoice: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    marginTop: spacing.xs,
    minHeight: 54,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  homeChoiceSelected: {
    borderColor: colors.accent,
    borderWidth: 2,
  },
  homeChoicePressed: {
    opacity: 0.72,
    transform: [{ scale: 0.99 }],
  },
  homeIcon: {
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: 10,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  homeIconText: {
    color: colors.accentDark,
    fontSize: 20,
    fontWeight: "900",
  },
  homeCopy: {
    flex: 1,
    marginLeft: spacing.sm,
  },
  homeTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  homeTitleSelected: {
    color: colors.accentDark,
  },
  homeMeta: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
  homeCheck: {
    color: colors.accentDark,
    fontSize: 18,
    fontWeight: "900",
    marginLeft: spacing.sm,
  },
  save: {
    marginTop: spacing.lg,
  },
});
